config/routes.rb
Rails.application.routes.draw do
  get 'rental/index'

  get 'rental/show/:id' => 'rental#show', :as => 'rental_show'

  resources :movies do
    get 'page/:page', :action => :index, :on => :collection
    resources :comments
  end
  get 'people/index'

  resources :products
  get 'home' => "page#home"

  get 'about_us' => "page#about_us"

  match "contact_us" => "page#contact_us", :via => [:post, :get]

  get 'newsletter' => "page#newsletter"

  get 'calendar(/:year(/:month))' => "page#calendar", :as => 'calendar'

  get 'articles' => "page#articles"

  get 'login' => "page#login"

  get 'teach' => "dustin#teach"

  get 'speak' => "dustin#speak"

  get 'dig' => "dustin#dig"

  get 'hello' => "say#hello"
  get 'goodbye' => "say#goodbye" #goodbye is method is say controller
  get 'something' => "say#something"

  root 'page#home'

end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @yo = "Yo Ho!"
    @now = Time.now
  end

  def goodbye

  end

  def something

  end

end

app/helpers/say_helper.rb
module SayHelper
end

app/views/say/goodbye.html.erb
<h1>Goodbye Dustin</h1>

app/views/say/hello.html.erb
<h1>Say#hello</h1>
<p>Find me in app/views/say/hello.html.erb</p>
Hello Dustin.
<br/>
<% 3.times do %>
    <%= 2+2 %>
    <p>HO!</p>
    <!--    <h2><%= @yo %></h2> -->
    <p><%= @now %></p>
<% end %>
<br/>
<div class="dustin">
<%= link_to "Teach Dustin", dustin_teach_path %>
</div>

app/views/say/something.html.erb
<h1>Do something Dustin!</h1>