config/routes.rb
Rails.application.routes.draw do
  get 'rental/index'

  get 'rental/show/:id' => 'rental#show', :as => 'rental_show'

  resources :movies do
    get 'page/:page', :action => :index, :on => :collection
    resources :comments
  end
  get 'people/index'

  resources :products
  get 'home' => "page#home"

  get 'about_us' => "page#about_us"

  match "contact_us" => "page#contact_us", :via => [:post, :get]

  get 'newsletter' => "page#newsletter"

  get 'calendar(/:year(/:month))' => "page#calendar", :as => 'calendar'

  get 'articles' => "page#articles"

  get 'login' => "page#login"

  get 'teach' => "dustin#teach"

  get 'speak' => "dustin#speak"

  get 'dig' => "dustin#dig"

  get 'hello' => "say#hello"
  get 'goodbye' => "say#goodbye" #goodbye is method is say controller
  get 'something' => "say#something"

  root 'page#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :movie

  def self.descending
    return order(:created_at=>:desc)
  end
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def full_name
    return first_name + " " + last_name
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :comments, :dependent => :destroy

  validates_presence_of :name, :director
  validates_numericality_of :year, :length, :greater_than => 0
  validates_uniqueness_of :name, :message => "is already used silly"
  validates_length_of :format, :maximum => 7, :minimum => 2
  def proper_name
    name.titleize
  end

  paginates_per 5

end

app/models/person.rb
class Person < ActiveRecord::Base
  def full_name
    return "#{first_name} #{last_name}"
  end

  def describe
    return "#{full_name} is #{age} years old and hair color is #{hair_color}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/usr.rb
class Usr < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/dustin_controller.rb
class DustinController < ApplicationController
  def teach
  end

  def speak
  end

  def dig
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, except:[ :index, :show ]

  # GET /movies
  # GET /movies.json
  def index
    #@page = params['page'] #page is a string variable
    #@prev_page = @page - 1 unless @page == 0
    #@next_page = @page + 1 unless (@page*5 > Movie.count)
    #@movies = Movie.limit(5).offset(@page * 5).order(:updated_at => :desc )
    @movies = Movie.page(params['page']).order(:updated_at => :desc)

  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @comment = Comment.new
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def authenticate
      authenticate_model! && current_model.try(:admin?)
    end

    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:name, :director, :description, :year, :length, :format, :image, :thumbnail)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def about_us
  end

  def contact_us
    @submitted = params["commit"]
    @name = params["name"]
    @form_error = false

    if @name == ""
     flash.now['error'] = "Must enter your name!"
      @form_error = true
    end

    @email = params["email"]
    @email_error = false

    if @email == ""
      @error_msgEmail = "Must enter your email!"
      @form_error = true
    end
    @question = params["question"]
    @newsletter = params["newsletter"] == 'newsletter'
    gender = params["gender"]
    @male = gender == "Male"
    @female = gender == "Female"
    @product = params["product"]
  end

  def products
  end

  def newsletter
  end

  def calendar
    @time = Time.now
    @month = params['month'].to_i
    @year = params['year'].to_i
    if ( !(@month >= 1 && @month <= 12) )
      @month = @time.strftime("%m").to_i
    end
    if ( @year <= 0 )
      @year = @time.strftime("%Y").to_i
    end
  end

  def articles
  end

  def login

  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end
end

app/controllers/rental_controller.rb
class RentalController < ApplicationController
  def index
    @movies = Movie.page(params['page']).order(:updated_at => :desc)
  end

  def show
    @movie = Movie.find( params['id'])
  end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @yo = "Yo Ho!"
    @now = Time.now
  end

  def goodbye

  end

  def something

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link_to(click_text, action, url, style)
    if action_name == action
      return link_to click_text, url, :class => style
    else
      return link_to click_text, url
    end
  end

  def stars( num_stars )
    return ((image_tag "star.jpg", :size=>"32x32")* num_stars).html_safe
  end

  def is_admin?
    return current_model.try(:admin?)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dustin_helper.rb
module DustinHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/page_helper.rb
module PageHelper

  def calendar( month, year )
    current_date = Date.new(year, month, 1)

    prev_month = month - 1
    prev_year = year
    if (prev_month <= 0)
      prev_month = 12
      prev_year = year - 1
    end

    next_month = month + 1
    next_year = year
    if (next_month > 12)
      next_month = 1
      next_year = year + 1
    end

    cal = current_date.strftime("%B")
    cal += "<br/>"
    cal += link_to "Prev", calendar_path(:month=> prev_month, :year => prev_year).to_s
    cal += link_to "   Next", calendar_path(:month=> next_month, :year => next_year).to_s
    day_of_week = current_date.strftime('%w').to_i
    cal += "<table border='1'>\n\t<tr>\n"
    days = %w(Sun Mon Tue Wed Thu Fri Sat)
    days.each do | day |
      cal += "\t\t<td>#{day}</td>\n"
    end

    # Second Row = first week of the month
    cal += "\t\t<tr>\n"
    day_of_week.times do
      cal += "\t\t\t<td>&nbsp;</td>\n"
    end

    # Print the days of week starting with 1

    (7 - day_of_week).times do | day|
      cal += "\t\t\t<td>#{day+1}</td>\n"
    end

    # Loop to do the in between rows


    # Final loop to do the last row
    # numbered till end of days, then blank days till end of month


    cal += "\t\t</tr>\n"
    cal += "\t</tr>\n</table>\n"
    cal += "Month: #{month}<br/>Year: #{year}<br/>"
    cal += "Date: #{current_date}<br/>"
    cal += day_of_week.to_s
    return cal
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/rental_helper.rb
module RentalHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Lecture</title>

  <%= stylesheet_link_tag "application", media: "screen", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "print", media: "print", "data-turbolinks-track" => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>

<div id="wrapper"><!-- #wrapper -->

  <header><!-- header -->
    <h1><a href="#">Cowboy Up</a></h1>
    <h2>Where the buffalo roam</h2>
    <%= image_tag "cowboyup.jpg", size: "940x200", alt: "Dustin's a Cowboy" %>
    <!--
    <img src="images/cowboyup.jpg" width="940" height="200" alt="">
    -->
  </header><!-- end of header -->
  <%= javascript_include_tag :defaults %>
  <%= render 'shared/nav' %><section id="main"><!-- #main content and sidebar area -->
    <section id="container"><!-- #container -->
      <section id="content"><!-- #content -->

  <%= yield %>



      </section><!-- end of #content -->
    </section><!-- end of #container -->

    <aside id="sidebar"><!-- sidebar -->
      <h3>Things To Do</h3>
      <ul>
        <li><a href="#">Play Games</a></li>
        <li><a href="#">Chat With Friends</a></li>
        <li><a href="#">Swap Stories</a></li>
        <li><a href="#">Sell Stuff</a></li>
        <li><a href="#">Buy Stuff</a></li>
        <li><a href="#">Trade Stuff</a></li>
      </ul>

      <h3>Our Sponsors</h3>
      <!--
      <img src="images/skis.jpg" alt="" /> <img src="images/skis.jpg" alt="" /><br />
      <img src="images/skis.jpg" alt="" /> <img src="images/skis.jpg" alt="" /><br /><br />
      -->
      <%= image_tag "movies/skis.jpg", alt: "" %>
      <%= image_tag "movies/skis.jpg", alt: "" %>
      <%= image_tag "movies/skis.jpg", alt: "" %>
      <%= image_tag "movies/skis.jpg", alt: "" %>
      <h3>Connect With Us</h3>
      <ul>
        <li><a href="#">Twitter</a></li>
        <li><a href="#">Facebook</a></li>
      </ul>

    </aside><!-- end of sidebar -->

  </section><!-- end of #main content and sidebar-->

  <footer>
    <section id="footer-area">

      <section id="footer-outer-block">
        <aside id="first" class="footer-segment">
          <h3>Blogroll</h3>
          <ul>
            <li><a href="#">one linkylink</a></li>
            <li><a href="#">two linkylinks</a></li>
            <li><a href="#">three linkylinks</a></li>
            <li><a href="#">four linkylinks</a></li>
            <li><a href="#">five linkylinks</a></li>
          </ul>
        </aside><!-- end of #first footer segment -->

        <aside id="second" class="footer-segment">
          <h3>Awesome Stuff</h3>
          <ul>
            <li><a href="#">one linkylink</a></li>
            <li><a href="#">two linkylinks</a></li>
            <li><a href="#">three linkylinks</a></li>
            <li><a href="#">four linkylinks</a></li>
            <li><a href="#">five linkylinks</a></li>
          </ul>
        </aside><!-- end of #second footer segment -->

        <aside id="third" class="footer-segment">
          <h3>Coolness</h3>
          <ul>
            <li><a href="#">one linkylink</a></li>
            <li><a href="#">two linkylinks</a></li>
            <li><a href="#">three linkylinks</a></li>
            <li><a href="#">four linkylinks</a></li>
            <li><a href="#">five linkylinks</a></li>
          </ul>
        </aside><!-- end of #third footer segment -->

        <aside id="fourth" class="footer-segment">
          <h3>Blahdyblah</h3>
          <p>Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.</p>
        </aside><!-- end of #fourth footer segment -->

      </section><!-- end of #footer-outer-block -->

    </section><!-- end of #footer-area -->
  </footer>

</div><!-- #wrapper -->
<!-- Free template created by http://freehtml5templates.com -->

</body>
</html>

app/views/page/about_us.html.erb
<h1>Page#about_us</h1>
<p>Find me in app/views/page/about_us.html.erb</p>

app/views/page/articles.html.erb
<h1>Page#articles</h1>
<p>Find me in app/views/page/articles.html.erb</p>

app/views/page/calendar.html.erb
<h1>Calendar</h1>

<%= calendar( @month, @year ).html_safe %>

app/views/page/contact_us.html.erb
<h1>Contact Us</h1>

Your name is: <%= @name %><br/>
Your email is: <%= @email %><br/>

<% if flash['error'] %>
    <div class='error'><%= flash['error'] %></div>

    <% end %>
<% if !@submitted || @form_error %>
    <!--
    <pre>
    <% params.each do |key, value| #DEBUGGING ONLY!!!!! %>
        <%= key + " ==> " + value %>
    <% end %>
    </pre>
    -->
    <%= form_for contact_us_path, :method => "POST" do %>
        <%= label_tag :name, "Enter your Full Name: " %>
        <%= text_field_tag :name, @name, :autofocus => "autofocus", :placeholder => "Enter your Name" %>
        <%= @error_msgName %>
        <br/>

        <%= label_tag :email, "Enter your Email Address: "%>
        <%= email_field_tag :email, @email, :placeholder => "something@domain.com"   %>
        <%= @error_msgEmail %>
        <br/>

        <%= label_tag :question, "Enter your Questions: " %><br/>
        <%= text_area_tag :question, @question, :size => "50x10" %>
        <br/>

        <%= check_box_tag :newsletter, "newsletter", @newsletter %>
        Subscribe to my newsletter?
        <br/>

        <%= radio_button_tag :gender, "Male", @male %> Male<br/>
        <%= radio_button_tag :gender, "Female", @female %> Female<br/>
        <%= select_tag :product, options_for_select(
                                       [
                                               ['Skis', 0],
                                               ['Poles', 1],
                                               ['Boots', 2],
                                        ], @product) %>
        <br/>
        <%= submit_tag "Ask Question" %>
    <% end %>
<% else %>
    Thanks for your information.
<% end %>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

app/views/page/login.html.erb
<h1>Page#login</h1>
<p>Find me in app/views/page/login.html.erb</p>

app/views/page/newsletter.html.erb
<h1>Page#newsletter</h1>
<p>Find me in app/views/page/newsletter.html.erb</p>

app/views/page/products.html.erb
<h1>Page#products</h1>
<p>Find me in app/views/page/products.html.erb</p>

app/views/shared/_nav.html.erb
<nav><!-- top nav -->
  <div class="menu">
    <ul>
      <li><%= nav_link_to "Home", "home", home_path, "current_page" %></li>
        <li><%= nav_link_to "About", "about", about_us_path, "current_page" %>
        <ul>
          <li><%= nav_link_to "Contact Us", "contact_us", contact_us_path, "current_page" %></li>
        </ul>
      </li>
      <!-- <li><\%= nav_link_to "Products", "products", products_path, "current_page" %></li> -->
      <li><%= nav_link_to "Calendar", "calendar", calendar_path, "current_page" %></li>
      <li><%= nav_link_to "Movies", "movies", movies_path, "current_page" %></li>
      <li><%= nav_link_to "Rentals", "rentals", rental_index_path, "current_page" %></li>
      <li><%= nav_link_to "Articles", "articles", articles_path, "current_page" %></li>
      <li><%= nav_link_to "Newsletter", "newsletter", newsletter_path, "current_page" %></li>

      <% if model_signed_in? %>
          <li><%= link_to "Logout", destroy_model_session_path, :method => :delete  %></li>
      <% else %>
          <li><%= link_to "Login", new_model_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav><!-- end of top nav -->
<% if model_signed_in? %>
    Welcome, <%= current_model.full_name %><br/>
<% end %>