config/routes.rb
Rails.application.routes.draw do
  get 'rental/index'

  get 'rental/show/:id' => 'rental#show', :as => 'rental_show'

  resources :movies do
    get 'page/:page', :action => :index, :on => :collection
    resources :comments
  end
  get 'people/index'

  resources :products
  get 'home' => "page#home"

  get 'about_us' => "page#about_us"

  match "contact_us" => "page#contact_us", :via => [:post, :get]

  get 'newsletter' => "page#newsletter"

  get 'calendar(/:year(/:month))' => "page#calendar", :as => 'calendar'

  get 'articles' => "page#articles"

  get 'login' => "page#login"

  get 'teach' => "dustin#teach"

  get 'speak' => "dustin#speak"

  get 'dig' => "dustin#dig"

  get 'hello' => "say#hello"
  get 'goodbye' => "say#goodbye" #goodbye is method is say controller
  get 'something' => "say#something"

  root 'page#home'

end

app/controllers/rental_controller.rb
class RentalController < ApplicationController
  def index
    @movies = Movie.page(params['page']).order(:updated_at => :desc)
  end

  def show
    @movie = Movie.find( params['id'])
  end
end

app/helpers/rental_helper.rb
module RentalHelper
end

app/views/rental/index.html.erb
<p id="notice"><%= notice %></p>
<% if is_admin? %>
    <h2>ADMIN!</h2>
    <%= link_to "Movies Admin", movies_path %>
    <% end %>

<h1>Listing movies</h1>
<div class='simple'>
  <%= paginate @movies %>
<%#= link_to "Prev", movies_path(:page => @prev_page) %> &nbsp;
<%#= link_to "Next", movies_path(:page => @next_page) %>

  <table border = 1>
    <thead>
    <tr>
      <th>Name</th>
      <th>Director</th>
      <th>Description</th>
      <th>Year</th>
      <th>Length</th>
      <th>Format</th>
      <th>Thumbnail</th>
      <th></th>


    </tr>
    </thead>

    <tbody>
    <% @movies.each do |movie| %>
        <tr>
          <td><%= movie.id %></td>
          <td><%= link_to movie.proper_name, rental_show_path( movie.id) %></td>
          <td><%= movie.director %></td>
          <td><%= truncate(movie.description.html_safe, :length => 20) %></td>
          <td><%= movie.year %></td>
          <td><%= movie.length %></td>
          <td><%= movie.format %></td>
          <td><%= link_to( image_tag(movie.image, :size => "70x70"), movie )  %></td>
          <td><%= link_to 'Show', rental_show_path( movie.id) %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/rental/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movie.proper_name %>
</p>

<p>
  <strong>Director:</strong>
  <%= @movie.director %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description.html_safe %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Length:</strong>
  <%= @movie.length %>
</p>

<p>
  <strong>Format:</strong>
  <%= @movie.format %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @movie.image %>
</p>

<p>
  <strong>Thumbnail image:</strong>
  <%= image_tag @movie.image %>
</p>

<h3>Comments</h3>
<% @movie.comments.descending.each do | comment | %>
    <h3><%= comment.title %></h3>
    <h3>about <%= time_ago_in_words(comment.created_at) %> ago, <%= comment.author %> said:</h3>
    <p><%= comment.content.html_safe %></p>
    <p>overall rating: <%= ((image_tag "star.jpg", :size=>"32x32")* comment.rating).html_safe %></p>
    <hr>
<% end %>


<%= link_to 'Back', rental_index_path %>